services:
  backend:
    build:
      context: ./RefugeBack
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://4.233.149.159:3310/refuge
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Not24Get!

  frontend:
    build:
      context: ./RefugeFront
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refuge
